#Configuracion estandar para levantar una imagen en docker de mongo
#Despues ejecutar: docker-compose up -d
version: '3'
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db